Query php version dynamically
yast/yast-http-server pull request #58
Opened 2022-07-27 09:53 UTC by mchf

## Problem

Php version was hardcoded. It caused troubles when php got new major update (php7 -> php8)

- https://bugzilla.suse.com/show_bug.cgi?id=1200016
- https://github.com/yast/yast-yast2/pull/1262

## Solution

Use newly implemented package search (see the referenced PR) for finding out accurate PHP version

## Testing

- Covered by existing tests
- *Tested manually*

2022-07-27 10:11 UTC, mvidner commented on src/modules/YaST/HTTPDPhpModule.pm
> +    @{$l} = sort @{$l};
So what happens when by_pattern returns `["php10", "php9"]`?

2022-07-28 06:22 UTC, mchf commented on src/modules/YaST/HTTPDPhpModule.pm
> +    @{$l} = sort @{$l};
it will work wrong
but we have php8 now so an issue happens in 2 versions ... in opposite to current state when an issue happens with each version ;-)

I'll master my perl skills one more time

2022-07-28 08:33 UTC, mvidner commented on src/modules/YaST/HTTPDPhpModule.pm
> +    return "" if(!$l);
why is this guard necessary?

2022-07-28 08:33 UTC, mvidner commented on src/modules/YaST/HTTPDPhpModule.pm
> +    @s = sort {$a <=> $b} @s;
so I find that Perl `sort` has the same wonderful property as JavaScript sort: it turns numbers to strings before sorting :rofl: 

```suggestion
    @s = sort {$a <=> $b} @s; # numeric sort, not stringified
```

2022-07-28 08:33 UTC, mvidner commented on src/modules/YaST/HTTPDPhpModule.pm
> +    return $s[-1];
what **should** this method return when it finds no PHP package at all?

2022-07-28 08:36 UTC, mvidner commented
My test script:

```pl
use strict;
use warnings;
use Data::Dumper;

my $l = ["php10", "php1", "php9"];
#my $l = [];

print Dumper($l);

my @s = map { int($_ =~ s/php([0-9]{1,2})$/$1/r) } @{$l};
print Dumper(\@s);

@s = sort @s;
print Dumper(\@s);

@s = sort {$a <=> $b} @s;
print Dumper(\@s);

print $s[-1], "\n";
```

output:
```
$VAR1 = [
          'php10',
          'php1',
          'php9'
        ];
$VAR1 = [
          10,
          1,
          9
        ];
$VAR1 = [
          1,
          10,
          9
        ];
$VAR1 = [
          1,
          9,
          10
        ];
10
```

2022-07-28 08:41 UTC, mchf commented on src/modules/YaST/HTTPDPhpModule.pm
> +    @s = sort {$a <=> $b} @s;
well perl was supposed for working with texts, wasn't it? ;-)

2022-07-28 08:49 UTC, mchf commented on src/modules/YaST/HTTPDPhpModule.pm
> +    return "" if(!$l);
a test was failing on "uninitialized $l" when no php was found

2022-07-28 08:51 UTC, mchf commented on src/modules/YaST/HTTPDPhpModule.pm
> +    return $s[-1];
something like ```nil``` would be nice, but rest of the code doesn't count with such situation (it expected a hard coded string before). So it depends how far we want to go when improving the code.

2022-07-28 08:54 UTC, mchf commented on src/modules/YaST/HTTPDPhpModule.pm
> +    @s = sort {$a <=> $b} @s;
btw if i'm not wrong the explicit cast to ```int``` is unnecessary and perl should handle strings starting with digits as numbers automatically.

2022-08-09 09:49 UTC, mvidner requested changes
now that the version method is not constant, use the precomputed value

2022-08-09 09:49 UTC, mvidner commented on src/modules/YaPI/HTTPDModules.pm
> +                    packages  => ["apache2-mod_php" . YaST::HTTPDPhpModule->Version()],
```suggestion
                    packages  => ["apache2-mod_php" . $php_version],
```

2022-08-09 09:51 UTC, mvidner approved these changes

2022-09-16 08:14 UTC, lslezak commented on src/modules/HttpServerPackages.rb
> +      Y2Packager::Resolvable.find({ kind: :package, provides_regexp: "^#{pattern}$" }, [])
More simplification:
```suggestion
      Y2Packager::Resolvable.find(kind: :package, provides_regexp: "^#{pattern}$")
```

2022-09-16 08:14 UTC, lslezak commented on src/modules/HttpServerPackages.rb
> +    publish function: :by_pattern, type: "list <string> (string)"
`by_provides_regexp`

2022-09-16 08:14 UTC, lslezak commented on test/routines_test.rb
> +      .to receive(:by_pattern)
`by_provides_regexp`

2022-09-16 09:56 UTC, lslezak approved these changes
LGTM

2022-09-16 10:09 UTC, merged